apiVersion: apps/v1
kind: Deployment
metadata:
  name: mood-inspiration-deployment
  labels:
    app: mood-inspiration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mood-inspiration
  template:
    metadata:
      labels:
        app: mood-inspiration
    spec:
      containers:
        - name: mood-inspiration-app
          image: mood-inspiration-app  # Ensure this matches your locally built image
          imagePullPolicy: Never  # Prevent Kubernetes from trying to pull from a remote registry
          ports:
            - containerPort: 5000
