apiVersion: v1
kind: Service
metadata:
  name: mood-inspiration-service
spec:
  selector:
    app: mood-inspiration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

